server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  application:
    name: ${SPRING_APPLICATION_NAME:ar_chemistry}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    open-in-view: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_wuMjdreND
  ai:
    openai:
      api-key: ${OPEN_ROUTER_API_KEY}

      # Route qua OpenRouter
      base-url: https://openrouter.ai/api

      chat:
        completions-path: /v1/chat/completions

        options:
          # Default model
          model: deepseek/deepseek-chat-v3-0324:free

          # Optional
          temperature: 0.7
          max-tokens: 1000

      embedding:
        options:
          model: openai/text-embedding-3-small
lbos:
  logging:
    logstash:
      host: ${LOGSTASH_HOST:localhost}
      port: ${LOGSTASH_PORT:5044}

logging:
  level:
    root: INFO
    com.chemistry.demo: INFO
    org.springframework.web: WARN

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  user_pool-id: ${AWS_USER_POOL_ID}

  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  temp-password: ${ADMIN_TEMPORARY_PASSWORD}

staff:
  email: ${STAFF_EMAIL}
  password: ${STAFF_PASSWORD}


