package com.chemistry.demo.enums;

public enum PermissionName {

    // USER
    MANAGE_USERS,
    VIEW_USERS,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    BLOCK_USER,
    UNBLOCK_USER,
    ASSIGN_ROLE,
    APPROVE_TEACHER,

    // CHEMICAL
    CREATE_CHEMICAL,
    VIEW_CHEMICAL,
    UPDATE_CHEMICAL,
    DELETE_CHEMICAL,
    IMPORT_CHEMICAL,
    EXPORT_CHEMICAL,
    MANAGE_CHEMICAL_STOCK,

    // REACTION
    CREATE_REACTION,
    VIEW_REACTION,
    UPDATE_REACTION,
    DELETE_REACTION,
    VERIFY_REACTION,
    APPROVE_REACTION,

    // AR
    SCAN_AR,
    UPLOAD_AR_MARKER,
    MANAGE_AR_CONTENT,
    DELETE_AR_CONTENT,

    // EXPERIMENT
    CREATE_EXPERIMENT,
    VIEW_EXPERIMENT,
    UPDATE_EXPERIMENT,
    DELETE_EXPERIMENT,
    MANAGE_LAB,

    // COURSE
    CREATE_COURSE,
    UPDATE_COURSE,
    DELETE_COURSE,
    VIEW_COURSE,
    JOIN_COURSE,
    ASSIGN_STUDENT,

    // REPORT
    VIEW_REPORTS,
    EXPORT_REPORTS,
    VIEW_STATISTICS,

    // SAFETY
    VIEW_SAFETY_GUIDE,
    MANAGE_SAFETY_GUIDE,
    REPORT_INCIDENT,
    VIEW_INCIDENT_REPORTS,

    // FILE UPLOAD
    UPLOAD_FILE,
    UPLOAD_EXERCISE_IMPORT,
    UPLOAD_DOCUMENT
}
