input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [timestamp] {
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }

  if ![level] {
    mutate {
      add_field => { "level" => "INFO" }
    }
  }

  if [execution_time] and ![durationMs] {
    mutate {
      rename => { "execution_time" => "durationMs" }
    }
  }

  if [method_name] and ![methodName] {
    mutate {
      rename => { "method_name" => "methodName" }
    }
  }

  if [serviceName] and ![className] {
    mutate {
      rename => { "serviceName" => "className" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ar-chemistry-be-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
